- name: add haproxy ppa repo
  apt_repository:
    repo: "ppa:vbernat/haproxy-2.0"
    state: present
    update_cache: yes
- name: install HAProxy-2.0 LTS
  apt:
    name: "haproxy=2.0.*"
    state: present
    install_recommends: yes

- name: haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -c -f %s

- name: restart HAProxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
